require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TesterAnswersController do

  # This should return the minimal set of attributes required to create a valid
  # TesterAnswer. As you add validations to TesterAnswer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TesterAnswersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tester_answers as @tester_answers" do
      tester_answer = TesterAnswer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tester_answers).should eq([tester_answer])
    end
  end

  describe "GET show" do
    it "assigns the requested tester_answer as @tester_answer" do
      tester_answer = TesterAnswer.create! valid_attributes
      get :show, {:id => tester_answer.to_param}, valid_session
      assigns(:tester_answer).should eq(tester_answer)
    end
  end

  describe "GET new" do
    it "assigns a new tester_answer as @tester_answer" do
      get :new, {}, valid_session
      assigns(:tester_answer).should be_a_new(TesterAnswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested tester_answer as @tester_answer" do
      tester_answer = TesterAnswer.create! valid_attributes
      get :edit, {:id => tester_answer.to_param}, valid_session
      assigns(:tester_answer).should eq(tester_answer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TesterAnswer" do
        expect {
          post :create, {:tester_answer => valid_attributes}, valid_session
        }.to change(TesterAnswer, :count).by(1)
      end

      it "assigns a newly created tester_answer as @tester_answer" do
        post :create, {:tester_answer => valid_attributes}, valid_session
        assigns(:tester_answer).should be_a(TesterAnswer)
        assigns(:tester_answer).should be_persisted
      end

      it "redirects to the created tester_answer" do
        post :create, {:tester_answer => valid_attributes}, valid_session
        response.should redirect_to(TesterAnswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tester_answer as @tester_answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        TesterAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:tester_answer => {}}, valid_session
        assigns(:tester_answer).should be_a_new(TesterAnswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TesterAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:tester_answer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tester_answer" do
        tester_answer = TesterAnswer.create! valid_attributes
        # Assuming there are no other tester_answers in the database, this
        # specifies that the TesterAnswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TesterAnswer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tester_answer.to_param, :tester_answer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tester_answer as @tester_answer" do
        tester_answer = TesterAnswer.create! valid_attributes
        put :update, {:id => tester_answer.to_param, :tester_answer => valid_attributes}, valid_session
        assigns(:tester_answer).should eq(tester_answer)
      end

      it "redirects to the tester_answer" do
        tester_answer = TesterAnswer.create! valid_attributes
        put :update, {:id => tester_answer.to_param, :tester_answer => valid_attributes}, valid_session
        response.should redirect_to(tester_answer)
      end
    end

    describe "with invalid params" do
      it "assigns the tester_answer as @tester_answer" do
        tester_answer = TesterAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TesterAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => tester_answer.to_param, :tester_answer => {}}, valid_session
        assigns(:tester_answer).should eq(tester_answer)
      end

      it "re-renders the 'edit' template" do
        tester_answer = TesterAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TesterAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => tester_answer.to_param, :tester_answer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tester_answer" do
      tester_answer = TesterAnswer.create! valid_attributes
      expect {
        delete :destroy, {:id => tester_answer.to_param}, valid_session
      }.to change(TesterAnswer, :count).by(-1)
    end

    it "redirects to the tester_answers list" do
      tester_answer = TesterAnswer.create! valid_attributes
      delete :destroy, {:id => tester_answer.to_param}, valid_session
      response.should redirect_to(tester_answers_url)
    end
  end

end
